---
- name: install homebrew packages
  homebrew: name={{ item }} state=latest update_homebrew=yes
  with_items: ['git', 'docker-machine', 'docker']

- name: docker
  local_action: osx_say msg="{{inventory_hostname}} is all done" voice=Zarvox